
# name: Build and Deploy
# on: [push]
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout ğŸ›ï¸
#         uses: actions/checkout@v2 

#       - name: Install and Build ğŸ”§ 
#         run: |
#           pnpm install
#           pnpm run build

#       - name: Deploy ğŸš€
#         uses: easingthemes/ssh-deploy@v2.1.1
#         with:
#           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#           BRANCH: gh-pages
#           FOLDER: dist
name: Node CI

on: [push]

jobs:
  build:
    # è¿è¡Œ ubuntuè™šæ‹Ÿæœºç³»ç»Ÿ
    runs-on: ubuntu-latest

    steps:
    - name: ä½¿ç”¨actionåº“ action/checkoutè·å–ä»£ç 
      uses: actions/checkout@v3
    - name: å®‰è£…node
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: å®‰è£…pnpm
      run: npm install -g pnpm  
    - name: å®‰è£…ä¾èµ–
      run: pnpm install --no-frozen-lockfile
    - name: æ‰“åŒ…
      run: pnpm run build
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"