
# name: Build and Deploy
# on: [push]
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout ğŸ›ï¸
#         uses: actions/checkout@v2 

#       - name: Install and Build ğŸ”§ 
#         run: |
#           pnpm install
#           pnpm run build

#       - name: Deploy ğŸš€
#         uses: easingthemes/ssh-deploy@v2.1.1
#         with:
#           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#           BRANCH: gh-pages
#           FOLDER: dist
name: Node CI

on: [push]

jobs:
  build:
    # è¿è¡Œ ubuntuè™šæ‹Ÿæœºç³»ç»Ÿ
    runs-on: ubuntu-latest

    steps:
    - name: è·å–ä»£ç 
    # ä½¿ç”¨actionåº“ action/checkoutè·å–ä»£ç 
      uses: actions/checkout@v3
    - name: å®‰è£…node
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: å®‰è£…pnpm
      run: npm install -g pnpm  
    - name: å®‰è£…ä¾èµ–
      run: pnpm install --no-frozen-lockfile
    - name: æ‰“åŒ…
      run: pnpm run build
    - name: éƒ¨ç½²åˆ°æœåŠ¡å™¨
      uses: avinal/github-pages-deploy-action@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        GITHUB_TOKEN: ${{ github.token }}
        MAKE_COMMAND: "make html"
        # Write the branch name for storing github pages source 
        PAGES_BRANCH: "gh-pages"
        # Write the branch name having source files for site/documentation
        BUILD_FROM: "main"
        # Write the name of the output folder where generated html is stored by makefile.
        DOCS_FOLDER: "dist"