name: Node CI

on: [push]

jobs:
  build:
    # 运行 ubuntu虚拟机系统
    runs-on: ubuntu-latest

    steps:
    - name: 使用action库 action/checkout获取代码
      uses: actions/checkout@v3
    - name: 安装node
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: 安装pnpm
      run: npm install -g pnpm  
    - name: 安装依赖
      run: pnpm install --no-frozen-lockfile
    - name: 打包
      run: pnpm run build
    - name: Deploy to Server
      uses: avinal/github-pages-deploy-action@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        GITHUB_TOKEN: ${{ github.token }}
        # MAKE_COMMAND: "make html"
        # Write the branch name for storing github pages source 
        PAGES_BRANCH: "gh-pages"
        # Write the branch name having source files for site/documentation
        BUILD_FROM: "main"
        # Write the name of the output folder where generated html is stored by makefile.
        DOCS_FOLDER: "dist"