
# name: Build and Deploy
# on: [push]
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout ğŸ›ï¸
#         uses: actions/checkout@v2 
name: è‡ªåŠ¨éƒ¨ç½²
on: [push]
jobs:
  build:
    # è¿è¡Œ ubuntuè™šæ‹Ÿæœºç³»ç»Ÿ
    runs-on: ubuntu-latest
    steps:
    - name: è·å–ä»£ç 
    # ä½¿ç”¨actionåº“ action/checkoutè·å–ä»£ç 
      uses: actions/checkout@v3
    - name: å®‰è£…node
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: å®‰è£…pnpm
      run: npm install -g pnpm  
    - name: å®‰è£…ä¾èµ–
      run: pnpm install --no-frozen-lockfile
    - name: æ‰“åŒ…
      run: pnpm run build
    - name: éƒ¨ç½²åˆ°æœåŠ¡å™¨
    - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/html
          config_file: Doxyfile
      # uses: avinal/github-pages-deploy-action@main
      # env:
      #   SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #   GITHUB_TOKEN: ${{ github.token }}
      #   MAKE_COMMAND: "make html"
      #   # Write the branch name for storing github pages source 
      #   PAGES_BRANCH: "gh-pages"
      #   # Write the branch name having source files for site/documentation
      #   BUILD_FROM: "main"
      #   # Write the name of the output folder where generated html is stored by makefile.
      #   DOCS_FOLDER: "dist"